name: "Domru Proxy"
version: "0.1.17"
slug: "domru_proxy"
description: "Reverse proxy for Domru API with authentication"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
panel_icon: mdi:camera
ingress: true
map:
  - data:rw
options:
  log-level: "info"
  refresh-token: ""
  operator-id: 0
schema:
  log-level: list(trace|debug|info|warn|error)
  refresh-token: password
  operator-id: int
ingress_port: 8080
ingress_entry: pages/home.html
ports:
  8080/tcp: null
ports_description:
  8080/tcp: "Web interface"
